{"stats": {"passes": 0, "skipped": 0, "encoding": "UTF-8", "errors": 1, "failures": 0, "total": 1}, "results": [{"name": "runTest", "tb": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/unittest/case.py\", line 329, in run\n    testMethod()\n  File \"/usr/local/lib/python2.7/dist-packages/nose-1.3.7-py2.7.egg/nose/loader.py\", line 418, in loadTestsFromName\n    addr.filename, addr.module)\n  File \"/usr/local/lib/python2.7/dist-packages/nose-1.3.7-py2.7.egg/nose/importer.py\", line 47, in importFromPath\n    return self.importFromDir(dir_path, fqname)\n  File \"/usr/local/lib/python2.7/dist-packages/nose-1.3.7-py2.7.egg/nose/importer.py\", line 94, in importFromDir\n    mod = load_module(part_fqname, fh, filename, desc)\n  File \"/home/talum/partial-derivatives-lab-data-science-pilot/test/index-tests.py\", line 2, in <module>\n    from ipynb.fs.full.index import (three_x_y_at_one, three_x_y_at_three, three_x_y_at_six,\nImportError: No module named ipynb.fs.full.index\n", "classname": "nose.failure:Failure", "time": 0.00019097328186035156, "errtype": "exceptions.ImportError", "type": "error", "message": "No module named ipynb.fs.full.index"}]}